name: My Github Actions Workflow
On: [Push]

jobs:
   testing_github:
     runs-on: ubuntu-latest
     steps:
       - name: Hello
         run: echo "Hello, Github Action"
       - name: Display Repository name
         run: echo "This Workflow is running in ${{ github.repository }}"